/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kijchat;
import java.net.*;
import java.io.*;
import java.util.*;


/**
 *
 * @author dimas
 */
public class Beranda extends javax.swing.JFrame {

    String text, username;
    KIJChatting User_Chat, tempKIJ;
    ArrayList<KIJChatting>Chat=new ArrayList();
    ArrayList<String>User=new ArrayList();
    ArrayList<String>User_name=new ArrayList();
    ArrayList<String>Public_Key=new ArrayList();
    int counter=0, i;
    Socket sock;
    BufferedReader reader;
    PrintWriter writer;
    /**
     * Creates new form Beranda
     * @param username
     */
    public Beranda(Socket sock, BufferedReader reader, PrintWriter writer, String username) {
        this.sock=sock;
        this.reader=reader;
        this.writer=writer;
        this.username=username;
        initComponents();
    }
    
    public void ShowActivity(String text){
        ActivityTextArea.append(text);
    }
    
    public void RemoveAllActivity(){
        ActivityTextArea.removeAll();
    }
    
    public void AddListUser(String user){
        ListUser1.add(user);
    }
    
    public void ClearListUser(){
        ListUser1.removeAll();
    }
    
    public void SendTo(String To, String Text){
        KIJChatting temp2;
        for(i=0; i<counter; i++){
            if(To.equals(User.get(i))){
                temp2=Chat.get(i);
                temp2.receive(To, Text);
            }
        }
    }
    
    public void adduser(String user){
        User_name.add(user);
    }
    
    public void addpublickey(String publickey){
        Public_Key.add(publickey);
    }
    
    public void removealluser(){
        
    }
    
    public void removeallpublic(){
        
    }
    
    public void sendDisconnect(){
        try{
            writer.println("DCON:"+username);
            writer.flush();
        }catch(Exception ex){
            ActivityTextArea.append("Tidak bisa mengirimkan Pesan Disconnect. \n");
        }
    }
    
    public void Disconnect(){
        try{
            ActivityTextArea.append("Disconnected.\n");
            sock.close();            
        }catch(Exception ex){
            ActivityTextArea.append("Gagal Untuk Disconnect. \n");
        }
        this.ClearListUser();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ActivityTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        chatButton = new javax.swing.JButton();
        ListUser1 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agent Orange", 1, 18)); // NOI18N
        jLabel1.setText("WELCOME TO CHAT KIJ");

        jLabel2.setText("UserOnline :");

        closeButton.setFont(new java.awt.Font("Agent Orange", 0, 18)); // NOI18N
        closeButton.setText("BACK");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        ActivityTextArea.setColumns(20);
        ActivityTextArea.setRows(5);
        jScrollPane1.setViewportView(ActivityTextArea);

        jLabel3.setText("Activity :");

        chatButton.setFont(new java.awt.Font("Agent Orange", 0, 18)); // NOI18N
        chatButton.setText("chat");
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(chatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ListUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        sendDisconnect();
        Disconnect();
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed
        // TODO add your handling code here:
        String PublicKey="";
        ActivityTextArea.append(ListUser1.getSelectedItem()+"\n");
        for(i=0;i<User_name.size();i++){
            ActivityTextArea.append("LIST:"+User_name.get(i)+"\n");
            if(ListUser1.getSelectedItem().equals(User_name.get(i))){
                PublicKey=Public_Key.get(i);
                ActivityTextArea.append("Public:"+PublicKey+"\n");
            }
        }
        tempKIJ=new KIJChatting(sock,reader,writer,ListUser1.getSelectedItem(),username,this, PublicKey);
        tempKIJ.setVisible(true);
        Chat.add(tempKIJ);
        User.add(ListUser1.getSelectedItem());
        counter++;
    }//GEN-LAST:event_chatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ActivityTextArea;
    private java.awt.List ListUser1;
    private javax.swing.JButton chatButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
