/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kijchat;
import java.net.*;
import java.io.*;
import java.util.*;


/**
 *
 * @author dimas
 */
public class KIJChatting extends javax.swing.JFrame {

    /**
     * Creates new form KIJChatting
     */
    RSA myRSA1=new RSA();
    RC4 myRC41=new RC4();
    Alpha random_key=new Alpha();
    String DefaultKey=random_key.randomString(10);
    Beranda Menu_Utama;
    Socket sock;
    BufferedReader reader;
    PrintWriter writer;
    String Recepient, Sender, Cipher, Key, e, n, PublicKey, Hash, Hash_new;
    public KIJChatting(Socket sock, BufferedReader reader, PrintWriter writer, String Recepient, String Sender, Beranda Menu_Utama, String PublicKey) {
        this.sock=sock;
        this.reader=reader;
        this.writer=writer;
        this.Sender=Sender;
        this.Recepient=Recepient;
        this.Menu_Utama=Menu_Utama;
        this.PublicKey=PublicKey;
        initComponents();
        withLabel.setText(Recepient);        
    }

    public void receive(String To, String Text){
        ChatArea.append(To+":"+Text+"\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChatArea = new javax.swing.JTextArea();
        SendField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        withLabel = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agent Orange", 0, 18)); // NOI18N
        jLabel1.setText("private chatting");

        ChatArea.setEditable(false);
        ChatArea.setColumns(20);
        ChatArea.setRows(5);
        jScrollPane1.setViewportView(ChatArea);

        sendButton.setFont(new java.awt.Font("Agent Orange", 0, 14)); // NOI18N
        sendButton.setText("send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        withLabel.setFont(new java.awt.Font("Agent Orange", 0, 14)); // NOI18N
        withLabel.setText("Hallo");

        CloseButton.setFont(new java.awt.Font("Agent Orange", 0, 14)); // NOI18N
        CloseButton.setText("close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SendField, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(withLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(CloseButton)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SendField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        String nothing="";
        if((SendField.getText()).equals(nothing)){
            SendField.setText(nothing);
            SendField.requestFocus();
        }
        else{
            try{
                //ChatArea.append("0\n");
                e=myRSA1.Get_ed_RSA(PublicKey);
                //ChatArea.append("1\n");
                n=myRSA1.Get_N_RSA(PublicKey);
                //ChatArea.append("2\n");
                Key=myRSA1.Enkripsi_RSA(DefaultKey, e, n);
                //ChatArea.append("3\n");
                Hash=myRC41.getMD5(SendField.getText());
                Cipher=myRC41.Enkripsi(SendField.getText(), DefaultKey);
                Hash_new=myRC41.Enkripsi(Hash, DefaultKey);
                //ChatArea.append("Sender"+e+":"+n+":"+Key+":"+Cipher+":\n");
                ChatArea.append("Succesfull Send Message\n");
                writer.println("SEND:"+Sender+":"+Recepient+":"+Cipher+":"+Key+":"+Hash_new+":");
                writer.flush();
                ChatArea.append(Sender+":"+SendField.getText()+"\n");
                Menu_Utama.ShowActivity("SEND FROM ="+Sender+" TO = "+Recepient+" : "+SendField.getText()+"\n");
            }catch(Exception ex){
                ChatArea.append("Pesan tidak dikirimkan. \n");
            }
        }
        SendField.setText(nothing);
        SendField.requestFocus();
    }//GEN-LAST:event_sendButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KIJChatting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KIJChatting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KIJChatting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KIJChatting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ChatArea;
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField SendField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel withLabel;
    // End of variables declaration//GEN-END:variables
}
